[build-system]
requires = [
         "setuptools>=43.0.0",
         "build",
         "wheel",
         "pyyaml",
         "pytest",
         "pytest-cov",
         "urllib3"
]
build-backend = "setuptools.build_meta"
